### ISSUE TITLE
error during renga init --autosync

### ISSUE THREAD

**Issue by andriineronov** [SwissDataScienceCenter/renga#106]
Following tutorial I got this error:

```
$ renga init --autosync
```

```python
Traceback (most recent call last):
  File "/Users/andriineronov/anaconda/envs/python3/bin/renga", line 11, in <module>
    sys.exit(cli())
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/cli/_config.py", line 82, in new_func
    result = ctx.invoke(f, config, *args, **kwargs)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/cli/init.py", line 74, in init
    project = client.projects.create(name=name)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/models/projects.py", line 42, in create
    data = self._client.api.create_project({'name': name})
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/api/projects.py", line 40, in create_project
    json=project, )
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/api/client.py", line 43, in decorator
    f(*args, **kwargs), expected_status_code)
  File "/Users/andriineronov/anaconda/envs/python3/lib/python3.5/site-packages/renga/errors.py", line 66, in return_or_raise
    raise cls(response)
renga.errors.UnexpectedStatusCode: Unexpected status code: 500
```

**Comment by jirikuncar** [comment]
@andriineronov can you please check that the platform itself is running: `make start`?
Did you get any error in the project service itself: `docker-compose logs projects`?

**Comment by andriineronov** [comment]
Yes, I have a message 

"Everything is up”

when I do "make start"

The output of docker-compose logs projects is attached

**Comment by jirikuncar** [comment]
@andriineronov unfortunately, the attachment is not visible on GitHub. Can you just paste few relevant lines?

**Comment by rokroskar** [comment]
this issue seems inactive, closing for now. @andriineronov please comment here and we can reopen it if you still want to try to resolve the issue.
