### ISSUE TITLE
quickstart: login yields internal server error

### ISSUE THREAD

**Issue by ltalirz** [SwissDataScienceCenter/renga#111]
I've been following the instructions to install renga locally on
http://renga.readthedocs.io/en/latest/user/setup.html#getting-the-code-and-images

Everything works fine and I can navigate to http://localhost/ui
Then, when I click on the "login" button below, I receive an internal server error (500).
![screen shot 2017-10-31 at 21 12 36](https://user-images.githubusercontent.com/1053245/32246739-40be55d8-be80-11e7-8fb9-3bc21aab1700.png)

The URL http://localhost/admin/swagger/ works fine.

I cannot connect via the python client,though:

```
$ renga login http://localhost
Username: demo
Password:
/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/api/client.py:83: UserWarning: Using insecure trasnport protocol, use HTTPS
  warnings.warn('Using insecure trasnport protocol, use HTTPS')
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/bin/renga", line 11, in <module>
    sys.exit(cli())
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/cli/_config.py", line 91, in new_func
    result = ctx.invoke(f, config, *args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/cli/login.py", line 58, in login
    scope=scope)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/api/authorization.py", line 62, in fetch_token
    return super(AuthorizationMixin, self).fetch_token(token_url, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 221, in fetch_token
    verify=verify, proxies=proxies)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/api/client.py", line 43, in decorator
    f(*args, **kwargs), expected_status_code)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/renga/errors.py", line 66, in return_or_raise
    raise cls(response)
renga.errors.UnexpectedStatusCode: Unexpected status code: 404
```

I'm running docker 17.09.0-ce-mac35 (19611) on MacOS 10.12.6 and am using the `master` branch.

**Comment by jirikuncar** [comment]
@ltalirz thank you for trying out the Renga platform. First, I would like to find out if it is a problem with Renga platform (`renga`) or the CLI (`renga-python`).

Start by removing old configuration (find the path by running):
```
$ renga --config-path
/Users/<NAME>/Library/Application Support/Renga/config.yml
```

Please upload logs to Gist or Pastebin from `docker-compose logs` and list of installed packages by running `pip freeze` and send us a link.

Then you can check if we have already fixed the platform by running `make wipe && docker-compose pull && make start` and also install the latest CLI by running `pip install -U -e git+https://github.com/SwissDataScienceCenter/renga-python.git#egg=renga`.

**Comment by ltalirz** [comment]
@jirikuncar thanks for having a look at this
I followed all your instructions, but unfortunately to no avail (the errors both in the web frontend and the cli remain the same).

Here the two logs you asked for:
https://gist.github.com/ltalirz/0aaa28a2f8a2d18475fbf3eba0810121
https://gist.github.com/ltalirz/bcffe7b02f0b1d32eaef239f5ccbcd36

I noticed one thing (perhaps unrelated):
I used to have to run all my docker commands via `sudo` (or they would simply hang).
After [removing the docker env variables from the .bashrc](https://forums.docker.com/t/docker-commands-require-sudo/12987) the problem is gone.
I did `make stop && make start` afterwards, however, and that didn't solve things.

**Comment by jirikuncar** [comment]
@ltalirz sorry for long delay. Please check if everything is running with `docker-compose ps`. The Java based services require quite some memory, which sometimes causes Keycloak to restart and makes the login endpoint unavailable.

**Comment by rokroskar** [comment]
@ltalirz looks like the keycloak service died -- we've found that this can happen if the docker daemon on mac os is not given enough memory. See the note under https://renga.readthedocs.io/en/latest/user/setup.html#prerequisites on how to fix this and then please try to restart the platform with `make wipe` and `make start`.

**Comment by ltalirz** [comment]
@jirikuncar @rokroskar Thanks for your help and my bad for overlooking this bit in the documentation. After setting the docker memory to 6GB, the problem is gone :)

I wonder:
 * could there be some way of checking at the time of installation whether there is enough memory available to run the application and print a warning otherwise?
 * on the web frontend, perhaps one could provide an "unreachable" error (or similar, I'm not an expert) when keycloak is not available, which would make it easier to track down the source of the problem. When I saw "internal server error" I didn't consider the possibility that the problem was just that one of the services was not running.

Anyhow, the original issue is resolved and can be closed.
